num_layers: 4
hidden_dim: 768
num_heads: 8
head_dim: 96
rope_dim: 96
kv_compression_dim: 64
query_compression_dim: 64
num_experts: 6
activated_experts: 2
dropout_rate: 0.1
vocab_size: 20000
min_seq_len: 5
max_seq_len: 128
stride: 32