vocab_size: 20000
hidden_size: 768
intermediate_size: 3072
moe_intermediate_size: 2048
num_hidden_layers: 12
num_attention_heads: 12
num_key_value_heads: 12
n_shared_experts: 1
n_routed_experts: 8
routed_scaling_factor: 2.5
kv_lora_rank: 64
q_lora_rank: 128
qk_rope_head_dim: 32
v_head_dim: 64
qk_nope_head_dim: 64
n_group: 2
topk_group: 1
num_experts_per_tok: 2
first_k_dense_replace: 2
norm_topk_prob: true
hidden_act: silu
max_position_embeddings: 128
initializer_range: 0.02
rms_norm_eps: 0.000001
use_cache: true
pad_token_id: 3
bos_token_id: 0
eos_token_id: 1
pretraining_tp: 1
tie_word_embeddings: false
rope_theta: 10000.0
rope_scaling:
  type: linear
  factor: 1.5
rope_interleave: true
attention_bias: false
attention_dropout: 0.0
